import asyncio
from decimal import Decimal

from sqlalchemy import select

from app.db.session import AsyncSessionLocal, engine
from app.models import Inventory, Product, ProductSpec


CATALOG = [
    {
        "product": {
            "slug": "apple-iphone-16-pro-max",
            "name": "iPhone 16 Pro Max",
            "brand": "Apple",
            "model": "iPhone 16 Pro Max",
            "price_vnd": 34990000,
            "description": "Apple flagship with a large ProMotion display and A18 Pro chip.",
            "image_url": "https://example.com/images/iphone-16-pro-max.jpg",
            "release_year": 2024,
        },
        "spec": {
            "chipset": "Apple A18 Pro",
            "ram_gb": 8,
            "storage_gb": 256,
            "screen_size_inches": Decimal("6.9"),
            "screen_type": "LTPO Super Retina XDR OLED",
            "refresh_rate_hz": 120,
            "battery_mah": 4685,
            "charging_watt": 30,
            "rear_camera": "48MP main + 48MP ultrawide + 12MP telephoto",
            "front_camera": "12MP TrueDepth",
            "os": "iOS 18",
            "gaming_score": Decimal("9.4"),
            "camera_score": Decimal("9.8"),
            "battery_score": Decimal("9.0"),
            "performance_score": Decimal("9.8"),
            "display_score": Decimal("9.7"),
        },
        "quantity": 18,
    },
    {
        "product": {
            "slug": "apple-iphone-16",
            "name": "iPhone 16",
            "brand": "Apple",
            "model": "iPhone 16",
            "price_vnd": 22990000,
            "description": "Compact iPhone with the A18 chip and a versatile dual camera.",
            "image_url": "https://example.com/images/iphone-16.jpg",
            "release_year": 2024,
        },
        "spec": {
            "chipset": "Apple A18",
            "ram_gb": 8,
            "storage_gb": 128,
            "screen_size_inches": Decimal("6.1"),
            "screen_type": "Super Retina XDR OLED",
            "refresh_rate_hz": 60,
            "battery_mah": 3561,
            "charging_watt": 25,
            "rear_camera": "48MP main + 12MP ultrawide",
            "front_camera": "12MP TrueDepth",
            "os": "iOS 18",
            "gaming_score": Decimal("8.9"),
            "camera_score": Decimal("9.0"),
            "battery_score": Decimal("8.5"),
            "performance_score": Decimal("9.2"),
            "display_score": Decimal("8.7"),
        },
        "quantity": 25,
    },
    {
        "product": {
            "slug": "samsung-galaxy-s25-ultra",
            "name": "Galaxy S25 Ultra",
            "brand": "Samsung",
            "model": "Galaxy S25 Ultra",
            "price_vnd": 33990000,
            "description": "Premium Android flagship with S Pen support and a high-resolution camera system.",
            "image_url": "https://example.com/images/galaxy-s25-ultra.jpg",
            "release_year": 2025,
        },
        "spec": {
            "chipset": "Snapdragon 8 Elite for Galaxy",
            "ram_gb": 12,
            "storage_gb": 256,
            "screen_size_inches": Decimal("6.9"),
            "screen_type": "Dynamic LTPO AMOLED 2X",
            "refresh_rate_hz": 120,
            "battery_mah": 5000,
            "charging_watt": 45,
            "rear_camera": "200MP main + 50MP ultrawide + 50MP periscope + 10MP telephoto",
            "front_camera": "12MP",
            "os": "Android 15",
            "gaming_score": Decimal("9.7"),
            "camera_score": Decimal("9.6"),
            "battery_score": Decimal("9.3"),
            "performance_score": Decimal("9.8"),
            "display_score": Decimal("9.8"),
        },
        "quantity": 16,
    },
    {
        "product": {
            "slug": "samsung-galaxy-s25-plus",
            "name": "Galaxy S25+",
            "brand": "Samsung",
            "model": "Galaxy S25+",
            "price_vnd": 26990000,
            "description": "Large-screen flagship balancing performance, battery life, and portability.",
            "image_url": "https://example.com/images/galaxy-s25-plus.jpg",
            "release_year": 2025,
        },
        "spec": {
            "chipset": "Snapdragon 8 Elite for Galaxy",
            "ram_gb": 12,
            "storage_gb": 256,
            "screen_size_inches": Decimal("6.7"),
            "screen_type": "Dynamic LTPO AMOLED 2X",
            "refresh_rate_hz": 120,
            "battery_mah": 4900,
            "charging_watt": 45,
            "rear_camera": "50MP main + 12MP ultrawide + 10MP telephoto",
            "front_camera": "12MP",
            "os": "Android 15",
            "gaming_score": Decimal("9.4"),
            "camera_score": Decimal("9.0"),
            "battery_score": Decimal("9.2"),
            "performance_score": Decimal("9.6"),
            "display_score": Decimal("9.5"),
        },
        "quantity": 21,
    },
    {
        "product": {
            "slug": "samsung-galaxy-a56-5g",
            "name": "Galaxy A56 5G",
            "brand": "Samsung",
            "model": "Galaxy A56 5G",
            "price_vnd": 11990000,
            "description": "Mid-range Samsung phone with a smooth display and long software support.",
            "image_url": "https://example.com/images/galaxy-a56-5g.jpg",
            "release_year": 2025,
        },
        "spec": {
            "chipset": "Exynos 1580",
            "ram_gb": 8,
            "storage_gb": 128,
            "screen_size_inches": Decimal("6.7"),
            "screen_type": "Super AMOLED",
            "refresh_rate_hz": 120,
            "battery_mah": 5000,
            "charging_watt": 45,
            "rear_camera": "50MP main + 12MP ultrawide + 5MP macro",
            "front_camera": "12MP",
            "os": "Android 15",
            "gaming_score": Decimal("8.0"),
            "camera_score": Decimal("8.0"),
            "battery_score": Decimal("9.0"),
            "performance_score": Decimal("8.1"),
            "display_score": Decimal("8.8"),
        },
        "quantity": 34,
    },
    {
        "product": {
            "slug": "xiaomi-15-ultra",
            "name": "Xiaomi 15 Ultra",
            "brand": "Xiaomi",
            "model": "Xiaomi 15 Ultra",
            "price_vnd": 29990000,
            "description": "Camera-focused flagship with Leica optics and fast charging.",
            "image_url": "https://example.com/images/xiaomi-15-ultra.jpg",
            "release_year": 2025,
        },
        "spec": {
            "chipset": "Snapdragon 8 Elite",
            "ram_gb": 16,
            "storage_gb": 512,
            "screen_size_inches": Decimal("6.73"),
            "screen_type": "LTPO AMOLED",
            "refresh_rate_hz": 120,
            "battery_mah": 5410,
            "charging_watt": 90,
            "rear_camera": "50MP main + 50MP ultrawide + 200MP periscope + 50MP telephoto",
            "front_camera": "32MP",
            "os": "Android 15",
            "gaming_score": Decimal("9.6"),
            "camera_score": Decimal("9.8"),
            "battery_score": Decimal("9.5"),
            "performance_score": Decimal("9.7"),
            "display_score": Decimal("9.6"),
        },
        "quantity": 12,
    },
    {
        "product": {
            "slug": "xiaomi-14t-pro",
            "name": "Xiaomi 14T Pro",
            "brand": "Xiaomi",
            "model": "Xiaomi 14T Pro",
            "price_vnd": 15990000,
            "description": "Performance-oriented value flagship with a bright 144Hz display.",
            "image_url": "https://example.com/images/xiaomi-14t-pro.jpg",
            "release_year": 2024,
        },
        "spec": {
            "chipset": "MediaTek Dimensity 9300+",
            "ram_gb": 12,
            "storage_gb": 512,
            "screen_size_inches": Decimal("6.67"),
            "screen_type": "AMOLED",
            "refresh_rate_hz": 144,
            "battery_mah": 5000,
            "charging_watt": 120,
            "rear_camera": "50MP main + 50MP telephoto + 12MP ultrawide",
            "front_camera": "32MP",
            "os": "Android 14",
            "gaming_score": Decimal("9.1"),
            "camera_score": Decimal("8.6"),
            "battery_score": Decimal("9.0"),
            "performance_score": Decimal("9.2"),
            "display_score": Decimal("9.1"),
        },
        "quantity": 27,
    },
    {
        "product": {
            "slug": "oppo-find-x8-pro",
            "name": "OPPO Find X8 Pro",
            "brand": "OPPO",
            "model": "Find X8 Pro",
            "price_vnd": 23990000,
            "description": "Premium OPPO phone with Hasselblad-tuned cameras and fast charging.",
            "image_url": "https://example.com/images/oppo-find-x8-pro.jpg",
            "release_year": 2024,
        },
        "spec": {
            "chipset": "MediaTek Dimensity 9400",
            "ram_gb": 16,
            "storage_gb": 512,
            "screen_size_inches": Decimal("6.78"),
            "screen_type": "LTPO AMOLED",
            "refresh_rate_hz": 120,
            "battery_mah": 5910,
            "charging_watt": 80,
            "rear_camera": "50MP main + 50MP ultrawide + 50MP periscope + 50MP telephoto",
            "front_camera": "32MP",
            "os": "Android 15",
            "gaming_score": Decimal("9.2"),
            "camera_score": Decimal("9.4"),
            "battery_score": Decimal("9.7"),
            "performance_score": Decimal("9.3"),
            "display_score": Decimal("9.3"),
        },
        "quantity": 14,
    },
    {
        "product": {
            "slug": "oppo-reno13-pro",
            "name": "OPPO Reno13 Pro",
            "brand": "OPPO",
            "model": "Reno13 Pro",
            "price_vnd": 14990000,
            "description": "Slim mid-range phone with a sharp portrait camera and durable design.",
            "image_url": "https://example.com/images/oppo-reno13-pro.jpg",
            "release_year": 2025,
        },
        "spec": {
            "chipset": "MediaTek Dimensity 8350",
            "ram_gb": 12,
            "storage_gb": 256,
            "screen_size_inches": Decimal("6.83"),
            "screen_type": "AMOLED",
            "refresh_rate_hz": 120,
            "battery_mah": 5800,
            "charging_watt": 80,
            "rear_camera": "50MP main + 50MP telephoto + 8MP ultrawide",
            "front_camera": "50MP",
            "os": "Android 15",
            "gaming_score": Decimal("8.3"),
            "camera_score": Decimal("8.7"),
            "battery_score": Decimal("9.3"),
            "performance_score": Decimal("8.4"),
            "display_score": Decimal("8.9"),
        },
        "quantity": 22,
    },
    {
        "product": {
            "slug": "google-pixel-9-pro-xl",
            "name": "Pixel 9 Pro XL",
            "brand": "Google",
            "model": "Pixel 9 Pro XL",
            "price_vnd": 26990000,
            "description": "Google flagship known for computational photography and a clean Android experience.",
            "image_url": "https://example.com/images/pixel-9-pro-xl.jpg",
            "release_year": 2024,
        },
        "spec": {
            "chipset": "Google Tensor G4",
            "ram_gb": 16,
            "storage_gb": 128,
            "screen_size_inches": Decimal("6.8"),
            "screen_type": "LTPO OLED",
            "refresh_rate_hz": 120,
            "battery_mah": 5060,
            "charging_watt": 37,
            "rear_camera": "50MP main + 48MP ultrawide + 48MP telephoto",
            "front_camera": "42MP",
            "os": "Android 14",
            "gaming_score": Decimal("8.2"),
            "camera_score": Decimal("9.7"),
            "battery_score": Decimal("8.9"),
            "performance_score": Decimal("8.5"),
            "display_score": Decimal("9.4"),
        },
        "quantity": 10,
    },
    {
        "product": {
            "slug": "google-pixel-9a",
            "name": "Pixel 9a",
            "brand": "Google",
            "model": "Pixel 9a",
            "price_vnd": 13990000,
            "description": "Compact Pixel with strong everyday photography and long software support.",
            "image_url": "https://example.com/images/pixel-9a.jpg",
            "release_year": 2025,
        },
        "spec": {
            "chipset": "Google Tensor G4",
            "ram_gb": 8,
            "storage_gb": 128,
            "screen_size_inches": Decimal("6.3"),
            "screen_type": "pOLED",
            "refresh_rate_hz": 120,
            "battery_mah": 5100,
            "charging_watt": 23,
            "rear_camera": "48MP main + 13MP ultrawide",
            "front_camera": "13MP",
            "os": "Android 15",
            "gaming_score": Decimal("7.8"),
            "camera_score": Decimal("9.0"),
            "battery_score": Decimal("9.0"),
            "performance_score": Decimal("8.0"),
            "display_score": Decimal("8.7"),
        },
        "quantity": 31,
    },
    {
        "product": {
            "slug": "apple-iphone-16e",
            "name": "iPhone 16e",
            "brand": "Apple",
            "model": "iPhone 16e",
            "price_vnd": 16990000,
            "description": "Accessible iPhone with the A18 chip and a lightweight design.",
            "image_url": "https://example.com/images/iphone-16e.jpg",
            "release_year": 2025,
        },
        "spec": {
            "chipset": "Apple A18",
            "ram_gb": 8,
            "storage_gb": 128,
            "screen_size_inches": Decimal("6.1"),
            "screen_type": "Super Retina XDR OLED",
            "refresh_rate_hz": 60,
            "battery_mah": 4005,
            "charging_watt": 25,
            "rear_camera": "48MP Fusion",
            "front_camera": "12MP TrueDepth",
            "os": "iOS 18",
            "gaming_score": Decimal("8.8"),
            "camera_score": Decimal("8.5"),
            "battery_score": Decimal("8.8"),
            "performance_score": Decimal("9.0"),
            "display_score": Decimal("8.5"),
        },
        "quantity": 29,
    },
    {
        "product": {
            "slug": "samsung-galaxy-z-flip7",
            "name": "Galaxy Z Flip7",
            "brand": "Samsung",
            "model": "Galaxy Z Flip7",
            "price_vnd": 28990000,
            "description": "Pocketable foldable phone with a useful cover display and flagship performance.",
            "image_url": "https://example.com/images/galaxy-z-flip7.jpg",
            "release_year": 2025,
        },
        "spec": {
            "chipset": "Snapdragon 8 Elite for Galaxy",
            "ram_gb": 12,
            "storage_gb": 256,
            "screen_size_inches": Decimal("6.9"),
            "screen_type": "Dynamic AMOLED 2X",
            "refresh_rate_hz": 120,
            "battery_mah": 4300,
            "charging_watt": 25,
            "rear_camera": "50MP main + 12MP ultrawide",
            "front_camera": "10MP",
            "os": "Android 15",
            "gaming_score": Decimal("8.9"),
            "camera_score": Decimal("8.7"),
            "battery_score": Decimal("8.2"),
            "performance_score": Decimal("9.4"),
            "display_score": Decimal("9.2"),
        },
        "quantity": 9,
    },
    {
        "product": {
            "slug": "xiaomi-redmi-note-14-pro-plus",
            "name": "Redmi Note 14 Pro+ 5G",
            "brand": "Xiaomi",
            "model": "Redmi Note 14 Pro+ 5G",
            "price_vnd": 10990000,
            "description": "Feature-rich mid-range phone with a high-resolution camera and fast charging.",
            "image_url": "https://example.com/images/redmi-note-14-pro-plus.jpg",
            "release_year": 2025,
        },
        "spec": {
            "chipset": "Snapdragon 7s Gen 3",
            "ram_gb": 8,
            "storage_gb": 256,
            "screen_size_inches": Decimal("6.67"),
            "screen_type": "AMOLED",
            "refresh_rate_hz": 120,
            "battery_mah": 5110,
            "charging_watt": 120,
            "rear_camera": "200MP main + 8MP ultrawide + 2MP macro",
            "front_camera": "20MP",
            "os": "Android 14",
            "gaming_score": Decimal("7.9"),
            "camera_score": Decimal("8.4"),
            "battery_score": Decimal("9.1"),
            "performance_score": Decimal("7.9"),
            "display_score": Decimal("8.9"),
        },
        "quantity": 38,
    },
    {
        "product": {
            "slug": "oppo-a5-pro",
            "name": "OPPO A5 Pro",
            "brand": "OPPO",
            "model": "A5 Pro",
            "price_vnd": 7990000,
            "description": "Durable everyday smartphone with a large battery and bright display.",
            "image_url": "https://example.com/images/oppo-a5-pro.jpg",
            "release_year": 2025,
        },
        "spec": {
            "chipset": "MediaTek Dimensity 6300",
            "ram_gb": 8,
            "storage_gb": 128,
            "screen_size_inches": Decimal("6.67"),
            "screen_type": "AMOLED",
            "refresh_rate_hz": 120,
            "battery_mah": 5800,
            "charging_watt": 45,
            "rear_camera": "50MP main + 2MP depth",
            "front_camera": "8MP",
            "os": "Android 15",
            "gaming_score": Decimal("7.1"),
            "camera_score": Decimal("7.2"),
            "battery_score": Decimal("9.0"),
            "performance_score": Decimal("7.0"),
            "display_score": Decimal("8.5"),
        },
        "quantity": 42,
    },
]


async def seed_catalog() -> tuple[int, int]:
    inserted = 0
    skipped = 0

    async with AsyncSessionLocal.begin() as session:
        for item in CATALOG:
            slug = item["product"]["slug"]
            existing = await session.scalar(select(Product).where(Product.slug == slug))
            if existing is not None:
                skipped += 1
                continue

            product = Product(
                **item["product"],
                spec=ProductSpec(**item["spec"]),
                inventory=Inventory(quantity=item["quantity"]),
            )
            session.add(product)
            inserted += 1

    return inserted, skipped


async def main() -> None:
    try:
        inserted, skipped = await seed_catalog()
        print(f"Catalog seed complete: inserted={inserted}, skipped={skipped}")
    finally:
        await engine.dispose()


if __name__ == "__main__":
    asyncio.run(main())
